model_list:
  # Primary Model
  - model_name: gpt-oss-120b
    litellm_params:
      model: gpt-oss-120b
      api_base: http://gpt-oss-120b:80

  # Secondary Models
  - model_name: qwen3-omni
    litellm_params:
      model: qwen3-omni
      api_base: http://qwen3-omni:80

  # Embeddings Model
  - model_name: embeddings
    litellm_params:
      model: nomic-embed-text
      api_base: http://embeddings-model:8083

router_settings:
  routing_strategy: simple-shuffle
  model_group_alias:
    vision: ["qwen3-omni"]
    text: ["gpt-oss-120b"]
    embedding: ["embeddings"]
  num_retries: 3
  timeout: 600
  fallbacks:
    - "gpt-oss-120b":
        - "qwen3-omni"

general_settings:
  master_key: sk-1234567890abcdef1234567890abcdef
  max_parallel_requests: 100
  enable_pre_call_checks: true
  telemetry: false