# Dockerfile for Ollama model containers
FROM ollama/ollama:latest

# Use a build argument to pass a variable
ARG BUILD_MODEL

# Set the environment variable for the model
ENV BUILD_MODEL=$BUILD_MODEL

# Use the build argument in a RUN command
#RUN echo "Using build variable: $BUILD_MODEL"

# Install bash and curl
RUN apt-get update && apt-get install -y bash curl

# Copy the start script
COPY start_model.sh /start_model.sh

# Make the script executable
RUN chmod +x /start_model.sh

# Set the script as the entrypoint
ENTRYPOINT ["/start_model.sh"]